<?php

require_once('inc/assist_just_giving_helpers.inc.php');

function assist_just_giving_node_presave($node) {
    if ($node->type == 'just_giving_batch') {
        $filename = file_load($node->field_file['und'][0]['fid'])->uri;
        $node->field_results['und'][0]['value'] = assist_just_giving_import($filename);
    }
}

function assist_just_giving_import($filename) {
    try {
        $extractor = new AssistJustGivingDataExtractor($filename);
        $communicator = new AssistJustGivingCommunicator();
        $contacts = $extractor->extractContacts();
        if ($map = $communicator->ensureContactsExistAndCreateMap($contacts)) {
            $donations = $extractor->extractDonations($map);
            $communicator->recordDonations($donations);
        }
        return $communicator->getFeedback();
    } catch(Exception $e) {
        return $e->getMessage();
    } 
}

class AssistJustGivingDataExtractor {
    private $justGivingIDFieldName = "custom_1";
    private $justGivingRows;
    public function __construct($filename) {
        $this->justGivingRows = AssistJustGivingHelpers::extractDataFromQuotedCSVFile($filename);
    }
    public function extractDonations($map) {
        $donations = array();
        foreach($this->justGivingRows as $row) {
            $donations[] = $this->extractDonation($row, $map);
        } 
        return $donations;
    }
    public function extractContacts() {
        $contacts = array();
        foreach($this->justGivingRows as $row) {
            if ($row['Fundraiser User Id']) {
                $fundraiserID = $row["Fundraiser User Id"];
                $contacts[$fundraiserID] = $this->extractContact($row, "Fundraiser");
            }
            if ($row["Donor E-mail"] !== "Anonymous") {
                $donorID = $row["Donor User Id"];
                $contacts[$donorID] = $this->extractContact($row, "Donor");
            }
        } 
        return $contacts;
    }  
    private function extractContact($row, $prefix) {
        return array(
            $this->justGivingIDFieldName => $row["$prefix User Id"],
            "contact_type" => "Individual",
            "first_name" => $row["$prefix FirstName"],
            "last_name" => $row["$prefix LastName"],
            "email" => $row["$prefix E-mail"],
            "postal_code" => $row["$prefix Postcode"],
            "city" => $row["$prefix Town"],
            "street_address" => $row["$prefix Address Line 1"],
            "supplemental_address" => $row["$prefix Address Line 2"],
            "location_type_id" => "Home",  
            "source" => "Just Giving Import " . date("Y-m-d")
        );
    }
    private function extractDonation($row, $map) {
        return array(
            "contact_id" => $map($row["Donor User Id"]),
            "total_amount" => $row["Net Donation Amount"],
            "financial_type" => "Donation"
        );
    }
}


class AssistJustGivingCommunicator {
    private $justGivingIDFieldName = "custom_1";
    private $feedback = null;

    private function formatError($errorString) {
        // Aim to change this wrapping to add colour via HTML
        return "***ERROR: $errorString ***";
    }

    public function getFeedback() {
        return $this->feedback;
    }

    public function ensureContactsExistAndCreateMap($contacts) {
        civicrm_initialize();
        $map = array();
        $success = true;
        foreach($contacts as $justGivingID => $contact) {
            try {
                if ($civiId = $this->findContactWithJustGivingID($justGivingID)) {
                    continue;
                } elseif ($civiId = $this->findContactAndAddJustGivingID($contact, $justGivingID)) {
                    $this->feedback .= "Added Just Giving ID $justGivingID to contact $civiId ... ";
                } else {
                    $civiId = $this->recordContact($contact);
                    $this->feedback .= "Created contact $civiId with Just Giving ID $justGivingID ... ";
                }
                $map[$justGivingId] = $civiId;
            } catch (Exception $e) {
                $this->feedback .= $this->formatError("Just Giving ID $justGivingID: " . $e->getMessage()) . " ... ";
                $success = false;
            }
        }
        if (!$success) {
            $this->feedback .= " INFO: NO DONATIONS ADDED DUE TO PRIOR ERRORS SHOWN ABOVE";
        }
        return $success ? $map : false;
    }

    private function recordContact($contact) {
        $civiContact = civicrm_api3('Contact', 'create', $contact); // doesn't handle address data...
        
        // ...so now also add address data
        $contact['contact_id'] = $civiContact['id'];
        civicrm_api3('Address', 'create', $contact);
        return $civiContact['id'];
    }
    private function recordDonations($donations) {
        try {
            forEach($donations as $donation) {
                civicrm_api3('Contribution', 'create', $donationData);
                $amount = $donation['total_amount'];
                $civiId = $donation['contact_id'];
                $this->feedback = "Added donation of $amount from contact $civiId ...";
            }
        } catch(Exception $e) {
            $this->feedback .= $this->formatError($e->getMessage()) . " ... ";
            $this->feedback .= "INFO: Recording donations aborted due to error. Please delete all donations that have been added before starting again.";
        }
    }
    private function findContactWithJustGivingID($justGivingID) {
        $results = civicrm_api3('Contact', 'get', array(
            "sequential" => 1,
            $this->justGivingIDFieldName => $justGivingID
        ));
        if ($results['count'] == 0) return false;
        return $results['values'][0]['id'];
    }
    private function findContactAndAddJustGivingID($contact, $justGivingID) {
        $candidates =  civicrm_api3('Contact', 'get', array(
            "first_name" => $contact["first_name"],
            "last_name" => $contact["last_name"],
            // This lets us match any email; just including it as
            // a field would only match primary
            "api.Email.get" => array("email" => $contact["email"])    
        ))["values"];
        // If there's more than one match, we don't care which one is used.
        foreach ($candidates as $candidate) {
            // Candidates are returned even if there is no match on
            // email, but email is returned only if it matches
            if ($candidate["api.Email.get"]["count"] > 0) {
                civicrm_api3("Contact", "create", array(
                    "id" => $candidate["id"],
                    $this->justGivingIDFieldName => $justGivingID
                ));
                return $candidate["id"];
            }
        }
    }
}
